### PR TITLE
Restrict devices to dri,input

### PR DESCRIPTION
**Pull request by Midar**
All is too broad and not needed.

### CODE REVIEW

**Comment by Midar** [comment]
Note: I was not able to test with a game pad, so I don't know if this game works with game pads at all. It might be possible to drop `input` if game pads don't work anyway.

**Comment by AsciiWolf** [comment]
Thanks for your PR. Game pads are supported by UT2004 and I have played it with one before. The "input" device permission is however not (yet) supported and since we definitely want to target even older Flatpak versions (for example the ones used by Steam Deck or Linux Mint), it would not be wise to merge this even if they were supported. Maybe after a year or two, but definitely not today.

**Comment by Midar** [comment]
I'll try with a game pad soon.

What I wonder is: How many people are there playing it with a game pad on Mint? I expect the number of people playing UT2004 of all games with a game pad quite low, and even lower the number of people playing it with a game pad on Mint. Maybe it's ok if users on Mint who want to play with a game pad then manually need to change `input` for `all` but everybody else benefits?

**Comment by AsciiWolf** [comment]
> How many people are there playing it with a game pad on Mint? I expect the number of people playing UT2004 of all games with a game pad quite low, and even lower the number of people playing it with a game pad on Mint. Maybe it's ok if users on Mint who want to play with a game pad then manually need to change input for all but everybody else benefits?

That does not matter. Removing a functionality is never a good solution. I am not merging this until the "input" device permission is widely used - and that can take several years. Sorry.

Also, I target mostly regular users with all of my Flatpaks, not Linux/Flatpak geeks who are skilled with the permission system and/or Flatseal.

**Comment by Midar** [comment]
I tried this with a game pad now and I couldn't get it to work despite enabling joystick in the settings. Are you sure this is working?

**Comment by AsciiWolf** [comment]
Yes, I am sure. I myself have played UT2004 using a game pad. It was 10 years ago or so, but I remember that it worked fine.

**Comment by Midar** [comment]
I verified that `/dev/input/event*` and `/dev/input/js*` are both available in the sandbox as well as generate events, however, UT2004 does not pick it up, or I'm doing it wrong. I went to the settings and enabled joystick support, then tried to bind a game pad button.

**Comment by Midar** [comment]
NVM, now it suddenly started working, I have no idea why.

**Comment by AsciiWolf** [comment]
By the way, [here](https://github.com/flatpak/flatpak/issues/5681) is a ticket related to the `device=all` vs `device=input` transition.

**Comment by Midar** [comment]
OK, while the buttons are picked up, the axis are broken on modern Linux. Left and right is mapped to analog triggers on my DualSense controller. There does not seem to be a way to remap this, so it's unplayable on modern Linux with at least that controller, but probably all controllers that expose the modern gamepad API of Linux.

**Comment by Midar** [comment]
BTW, the documentation says this:

> Using newer permissions like input or usb will have no effect on older Flatpak versions and will fail when used through Flatpak commandline.

So it seems like adding `input` will not fail on older versions and just work? With that in mind, I think the not-all that is only respected by newer versions could work.

**Comment by AsciiWolf** [comment]
> So it seems like adding `input` will not fail on older versions and just work? With that in mind, I think the not-all that is only respected by newer versions could work.

Please read the ticket I linked before. This "transitional thing" is planned (proposed), however it is not supported yet.

Also, the way it will work is that instead of replacing the `--device=all` permission, you will also add `--device=input` and `--device=not-all,input`. The "all" device permission will continue to work on older Flatpak versions, however if the "input" device permission will be used instead (as indicated using the `not-all,input` permission) with newer ones.

Anyway, there is no point in discussing this further until this proposal gets accepted and implemented and also until other Flathub Flatpaks will start implementing it into their manifests instead of just using `--device=all`.

I am closing this PR. Thanks again for your work and feel free to re-submit the PR after the proposal is accepted and implemented or after the current Flatpak versions (that do not support `--device=input`) are obsolete and not used anymore.

**Comment by AsciiWolf** [comment]
By the way, just a small tip. If you want to make the UT2004 Flatpak more secure on your own machine, you can download [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and change its `--device=all` permission to `--device=dri` there.

**Comment by Midar** [comment]
I know, that's how I tested :).

I suppose in order to make game pads work on modern Linux again, a wrapper is required that catches open of `/dev/input/js*`, opens the corresponding `/dev/input/event*` and translates the events. It looks like `ABS_X` and `ABS_Y` are already mapped to axes 0 and 1, but `ABS_RX` and `ABS_RY` would need to be mapped to axes 2 and 3. It seems the problem is that in evdev order, there is `ABS_Z` in between. `ABS_Z` and `ABS_RZ` should probably just be mapped to buttons TL and TR, respectively.

Without this, game pad support probably is currently broken for probably around 99% of game pads out there.

**Comment by Midar** [comment]
I've now also tested with a controller using the Xbox 360 controller profile (also known as an XInput controller). This makes up for around 98% of controllers out there. It's broken the same way as the DualSense, which means game pad support is currently just broken, period.

Given that, is there any reason to allow sandbox access to all devices if the only thing it is being used for (game pad support) is currently completely broken anyway?

**Comment by Midar** [comment]
OK, looking further, this seems to be a bug in the game outright that was always there, it's just being manifested now by Linux having changed to a more consistent controller profile. Here's what the SDL documentation says:

> SDL makes no promises about what part of the joystick any given axis refers to. Your game should have some sort of configuration UI to let users specify what each axis should be bound to. Alternately, SDL's higher-level Game Controller API makes a great effort to apply order to this lower-level interface, so you know that a specific axis is the "left thumb stick," etc.

So UT2004 really should offer a way to remap axes, however, it does not seem to provide such functionality. Unfortunately, UT2004 predates probably both, SDL's Game Controller API as well as evdev, which results in it no longer working properly today.

**Comment by AsciiWolf** [comment]
Thanks for the testing. I will keep the "all" device permission for now and will do further testing including Steam Deck when I have access to one (because I am pretty sure that some of this Flatpak users have confirmed that it works for them on Steam Deck and I doubt that they were using keyboard and mouse).

I will also test the same thing with my other [Unreal Tournament 99](https://github.com/flathub/com.epicgames.ut99) Flatpak.

**Comment by Midar** [comment]
UT99 has the same axes problem, just differently. But they're also all wrong. If this only works on the Steam Deck, isn't the Steam Deck new enough for `input`?

I also tried UT99 in Wayland and it just crashed.

**Comment by Midar** [comment]
I don't think it's a problem with my system but rather that UT is using the joystick API, while Linux migrated to this API: https://github.com/torvalds/linux/blob/master/Documentation/input/gamepad.rst

The new API is available via `/dev/input/event*`, while the old one is `/dev/input/js*`. SDL's Joystick API, which I believe uses the old Linux API, explicitly says:

> SDL makes no promises about what part of the joystick any given axis refers to. Your game should have some sort of configuration UI to let users specify what each axis should be bound to. Alternately, SDL's higher-level Game Controller API makes a great effort to apply order to this lower-level interface, so you know that a specific axis is the "left thumb stick," etc.

So this is very much a case of UT holding it wrong. It should have a UI to select which axes to use.

As for `input` not being supported in any released Flatpak version, that is incorrect. I believe you confuse it with `usb`, which was indeed introduced in 1.15.11 (which has been released, though). `input` was introduced in 1.15.6 and ArchLinux seems to be at 1.15.10, so it should work on the Steam Deck.

In any case, I don't believe this is a problem with my system, as  I wrote an abstraction library for gamepads and had multiple people test it with different controllers on multiple very different systems and this pretty much matches the behavior I've seen a lot. What I also know from this is that 95% of controllers identify as an XInput controller, which all use the Xbox 360 profile in Linux. And the other 5% are Sony, Nintendo and Stadia controllers. The Steam Deck was something else entirely, but in the end also supported the Xbox 360 profile IIRC. In any case, since not only the XInput controllers were broken, but also the Sony ones, this means effectively, gamepad support is broken on all controllers in UT with a modern Linux kernel. Nintendo controllers *might* just work out of pure luck since they lack analog triggers. I don't remember if the Steam Deck has analog triggers, if it doesn't, it might just work there out of pure luck, too.

**Comment by AsciiWolf** [comment]
> I don't think it's a problem with my system but rather that UT is using the joystick API, while Linux migrated to this API

Well, even if it really was broken (including Steam Deck), I am not removing the `all` device permission at the moment because it would require further testing from my side. I am not able to provide any in upcoming month or two because I am not at home and have only my laptop with low-end GPU and no gamepad here with me. Also, my time is very limited now.

> As for input not being supported in any released Flatpak version, that is incorrect. I believe you confuse it with usb, which was indeed introduced in 1.15.11 (which has been released, though). input was introduced in 1.15.6 and ArchLinux seems to be at 1.15.10, so it should work on the Steam Deck.

Keep in mind that 1.15.x is a development release + it also needs corresponding xdg-desktop-portal(-gtk) versions.

By the way, I believe that more than 80% of other Flathub games also have the `all` device permission at the moment.

**Comment by Midar** [comment]
I have written a [library](https://github.com/Midar/UTGamepad) that can be injected that replaces the SDL joystick methods with calls into my gamepad abstraction library and it works. However, one bug remains: Walking works at expected speeds, however, looking with the gamepad is extremely slow and I found no way around it, despite the maximum/minimum value being returned.

**Comment by Midar** [comment]
Further research shows that the SDLDrv and WinDrv for UT99 is source available (not open source, though). Looking at the code, the bug becomes obvious immediately: The SDLDrv devices so that the range is between -1 and 1, while WinDrv uses a range between -(2^31) and (2^31)-1.

Unfortunately, no such code is available for UT2004. But given it was AFAIK done by the same person (probably without ever testing joysticks) and shows the same symptoms, I'm sure UT2004 has the same issue. Given Epic has not allowed the community to maintain UT2004, unlike UT99, UT2004 will forever have broken, unfixable joystick support unless we binary patch it.

I think it is therefore pretty obvious that gamepads never could have worked in UT2004 and the permission should be dropped. Are you sure you used it 10 years ago with this Linux version? Maybe you were running the Windows version in Wine, exactly to make the gamepad work?

**Comment by AsciiWolf** [comment]
I need to test it on a Steam Deck and also on my Linux desktop first. But that won't happen in less than two months.

**Pull request closed without merging**
