### PR TITLE
Use Wayland if available

### PR DESCRIPTION
**Pull request by Midar**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks for your PR. I already tested this when I was working on this Flatpak and it did not work well. Even if it works now, it still needs another extensive testing before it can be merged.

**Comment by Midar** [comment]
I tried running it for quite a while without any isuses. What issues were you running into?

What extensive testing would be required? I tried it on Mutter running on amdgpu with the actual rendering being done by the proprietary NVIDIA driver.

**Comment by AsciiWolf** [comment]
I am currently not at home and won't be there for at least another month or so, so I am limited with my testing to only using my integrated Intel GPU.

I did some brief testing and everything seems to work fine now. I had multiple graphical glitches and a mouse input bugs when I last tried in 2023 (with my home PC running AMD GPU).

I am merging this. Let's hope it won't create any regressions.

Thanks!

**Comment by Midar** [comment]
Thx for merging!

I don't know much about flatpak, but now my `/var/lib/flatpak/app/com.epicgames.ut2004/x86_64/stable/b782f72e1861520f308f82082cd54b2d7fa34478ac9463e80baec070ae2457b3/metadata` contains:

`sockets=x11;wayland;pulseaudio;fallback-x11;`

I think x11 should not be in there, because otherwise it will allow to use x11 on Wayland. I think without setting `SDL_VIDEODRIVER`, this will then use X11, even on Wayland, depending on the SDL version. And adding `SDL_VIDEODRIVER` to Wayland would break X11, obviously. So I think the best way to use Wayland on Wayland and X11 on X11 would be to only allow `fallback-x11` and not `x11`.

This seems to be the case in `master`, but not what I got from flathub?

**Comment by AsciiWolf** [comment]
I think that this is a bug (or a feature) in Flatpak. Although the x11 socket is also added, wayland seems to be correctly used instead, at least on my system.

**Comment by Midar** [comment]
Looking through the documentation, this might be why:

> --socket=fallback-x11 - Show windows using X11, if Wayland is not available, overrides x11 socket permission. Note that you must still use --socket=wayland for wayland permission

So it seems `fallback-x11` removes `x11`, so all should be fine.

I now also tested with just amdgpu and that worked as well flawlessly. What I haven't tried yet is a pure NVIDIA system - I might be able to simulate that on my laptop by using the MUX in the UEFI.

**Pull request merged**
